### ISSUE TITLE
Bug in merging pipe and compressors

### ISSUE THREAD

**Issue by kaarthiksundar** [lanl-ansi/GasModels.jl#100]
@rb004f 

There is a bug in merging pipes and compressors into connections. Since the pipe id and compressor id are the same, merging same id pipes and compressor will omit one of the components. For instance, check the 24-pipeline-benchmark. After merging, the connections will not miss 5 components. I think this bug propagates to the constraints and variables as well.

**Comment by rb004f** [comment]
Given that we want to support an in memory data structure that collects all edge elements and there are variables (and other) things that are common to all edges (such as flux variables), the ids of connection elements should be unique, otherwise there will be unexpected behavior. To address this issue, a check was added to the code that will produce an error message if there are any non unique connection ids.  The code will continue to run, but the user is advised that the result may not be what the expect.
