### ISSUE TITLE
Data format updates

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#39]
- [x] status flag on input for all component types
- [x] field names for x,y coordinates
- [x] load values in output data of LS model

**Comment by rb004f** [comment]
@ccoffrin What is the use case for GasModels.jl computation needing x,y coordinates?

**Comment by ccoffrin** [comment]
It is not required for the computation, but experience on power networks would suggest it is valuable to have as optional parameters on the nodes of a network.

Also, in the near term we need a standard name here to support basic visualizations.

**Comment by rb004f** [comment]
Ok, I am not 100% convinced this is the right place to do (x,y) since GasModels.jl really won't use the data.... 

But, are you thinking that these should be fields in the matlab format?  If so, we should think carefully if that is where we want to put that data since doing "GIS" right requires additional information like coordinate system, projection, etc....
