### ISSUE TITLE
Json Data: Component ids... Strings or Integers

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/GasModels.jl#48]
The internal data structures of GasModels.jl assume all component ids are integers, however the json data input format uses strings for component ids, but all references to these ids use their integer equivalent.  This should be unified as strings or integers, not a mix.

**Comment by ccoffrin** [comment]
Part of the issue is that int keys are preferable for fast comparison, but only string keys are supported by JSON.  In PowerModels we try to have the best of both worlds by,
- all objects hold an "index" value, which is int
- the core "data" object is JSON serializable (i.e. string lookups) 
- the internal "ref" data structure provides [int => component lookups](https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/base.jl#L220)

Internally PowerModels will always use "ref" and not "data" (effectively standardizing around Int), but users primarily interact with "data".

**Comment by rb004f** [comment]
Stale issue
