### ISSUE TITLE
Status Value Consistency

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#49]
Questions
- Should the field be optional or required?
- Should the value be 0/1 or false/true?

The PowerModels convention is,
- required for all compenents
- values are in 0/1 to play nice with Matlab data formats, where data tables cannot have mixed types

**Comment by rb004f** [comment]
I think in both cases GasModels and PowerModels should adopt the same conventions. 

The first point is a little subtle.  Are you referring to status being an optional parameter for the internal data structures or for the data files?  I suspect the former since some of the input data files PowerModels supports doesn't have explicit status fields for all components.  Is it then the responsibility of the io implementation to fill in appropriate status values if the data format does not support it? 

Similarly, the internal data structures of GasModels assume status is a required field, and build_ref fills in default values for status. To be consistent with PowerModels, perhaps that should also be taken care of at the io level.  And, since we are defining the json input schema, we can make it a required field (?) for the json io...

I don't have strong feels on point 2.  true/false feels more intuitive for human readers, but I am fine either way.

**Comment by rb004f** [comment]
I believe this has been addressed through adoption of the PowerModels.jl convention.  Closing the issue
