### ISSUE TITLE
Fix case on instruction to install AmplNLWriter

### ISSUE THREAD

**Issue by 3ch01c** [lanl-ansi/GasModels.jl#98]
Not sure how [this test](https://github.com/lanl-ansi/GasModels.jl/blob/79ceeb7a4d618aa5a1e9b9d8be0898b8205be374/test/runtests_long.jl#L28) works, but if `AmplNLWriter` package isn't installed, it says to `Pkg.add("AMPLNLWriter")` which fails to resolve due to case sensitivity. It should be `Pkg.add("AmplNLWriter")`

**Comment by ccoffrin** [comment]
I can't find any place in the code with `AMPLNLWriter` instead of `AMPLNLWriter`, so I am at a loss for how to fix this.

**Comment by 3ch01c** [comment]
It might be an issue with JuMP or something. I'm pretty sure it's happening on [that test](https://github.com/lanl-ansi/GasModels.jl/blob/79ceeb7a4d618aa5a1e9b9d8be0898b8205be374/test/runtests_long.jl#L28), though. FWIW the issue is occurring in a Win 10 environment.

**Comment by rb004f** [comment]
Can you send a trace of your output? As you can see from the test file, we are using

```
using AmplNLWriter
```

with the correct case sensitivity.

We run those tests locally cross platform (including windows 10) because they take too long for travis without issue.  We do typically use SCIP to keep the tests running in under an hour, but couenne  works through the AmplNLWriter (albeit with a many hour run time)

Given the ```Pkg.add("AmplNLWriter")``` syntax you aren't by chance using Julia < 1.0? We recently dropped support for Julia 0.6 and 0.7 and the use the new package manager system.

**Comment by 3ch01c** [comment]
Using [Julia 1.1.1 build](https://julialang-s3.julialang.org/bin/winnt/x64/1.1/julia-1.1.1-win64.exe) and latest builds of everything else on a clean Win10 64-bit VM. I'll post a trace when I can.

**Comment by 3ch01c** [comment]
I think the issue here is with the above commits. It looks like I was able to resolve this issue by installing the latest version of the GasModels package directly (i.e., `add https://github.com/lanl-ansi/GasModels.jl`) from this repository instead of using the version in [Julia Registry](https://github.com/JuliaRegistries/General/blob/master/G/GasModels/Versions.toml#L25) (i.e., `add GasModels`).

**Comment by ccoffrin** [comment]
Ok, so it seems like tagging v0.4.1 would resolve this issue.  @kaarthiksundar @rb004f any reason not to tag?  The commits since the last release appear to be non-breaking.

**Comment by kaarthiksundar** [comment]
@ccoffrin I am fine.

**Comment by 3ch01c** [comment]
Looks like the issue is resolved in v0.4.1.
